instrumentation-test:
  type: instrumentation
  app: app/build/outputs/apk/debug/app-debug.apk
  test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  device:
    - model: Nexus5
      version: 21
      locale: ja_JP
      orientation: portrait
    - model: mata
      version: 25
      locale: ja_JP
      orientation: portrait